In [147]:
import pandas as pd

In [180]:
df = pd.read_csv('covid_toy.csv')
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [206]:
### top data check , we will use df.head() , by default it returns top 5 rows.
df.head(2)

   age  gender  fever  cough  city  has_covid
0   60       0  103.0      0     0          0
1   27       0  100.0      0     2          1

In [207]:
### bottom data chrck,we will use df.tail() , by default it returns last 5 rows.
df.tail(3)

    age  gender  fever  cough  city  has_covid
97   20       1  101.0      0     1          0
98    5       1   98.0      1     3          0
99   10       1   98.0      1     0          1

In [208]:
### If you want random indexed data , then we will use df.sample().By default it will
# return single row.
df.sample()

    age  gender       fever  cough  city  has_covid
94   79       0  100.844444      1     0          1

In [182]:
# if we want to check data type of each column -> df.dtypes
df.dtypes

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [183]:
# if we want to check overall information then we will use df.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [184]:
# x = 0-100
# 50% = 50 
# x = 1,2,3,4,5
# mean = (1+2+3+4+5)/5 = 15/5 = 3

In [185]:
# if you want to check statical view of data, then you can use -> df.describe() 
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [186]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [187]:
# if you want to check missing data in df, then you will use df.isnull().sum() 
df.isnull().sum()  ## here fever has 10 missing values

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [188]:
# x = 1,2,3,NaN,5
# mean = (1+2+3+5)/4 = 11/4 = 2.75 
# we will fill this value in this missing data 
# x = 1,2,3,2.75,5

In [189]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [190]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [191]:
df.head(1)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No

In [192]:
# if you have categorical data, and you want to check total sub-categories
# then we will use df['column_name'].value_counts()
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [193]:
# machine ---> Numbers --->

In [194]:
df['gender'] = df['gender'].map({'Female':1,'Male':0})

In [195]:
df.head(5)

   age  gender  fever cough     city has_covid
0   60       0  103.0  Mild  Kolkata        No
1   27       0  100.0  Mild    Delhi       Yes
2   42       0  101.0  Mild    Delhi        No
3   31       1   98.0  Mild  Kolkata        No
4   65       1  101.0  Mild   Mumbai        No

In [196]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [197]:
df['cough'] = df['cough'].map({'Mild':0, 'Strong':1})

In [198]:
df.sample(5)

    age  gender  fever  cough       city has_covid
46   19       1  101.0      0     Mumbai        No
32   34       1  101.0      1      Delhi       Yes
53   83       0   98.0      0      Delhi       Yes
57   49       1   99.0      1  Bangalore        No
20   12       0   98.0      1  Bangalore        No

In [199]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [202]:
df['city'] = df['city'].map({'Kolkata':0, 'Bangalore':1, 'Delhi':2, 'Mumbai':3})

In [203]:
df.sample(5)

    age  gender  fever  cough  city has_covid
74   34       1  104.0      1     2        No
42   27       0  100.0      0     2       Yes
16   69       1  103.0      0     0       Yes
71   75       1  104.0      1     2        No
1    27       0  100.0      0     2       Yes

In [204]:
df['has_covid'] = df['has_covid'].map({'No':0,'Yes':1})

In [205]:
df.sample(5)

    age  gender  fever  cough  city  has_covid
20   12       0   98.0      1     1          0
78   11       0  100.0      0     1          1
64   42       0  104.0      0     3          0
30   15       0  101.0      0     2          1
58   23       0   98.0      1     3          1