In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("placement - placement.csv")
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [3]:
# x = df.astype(int)  type conversion
df['cgpa'] = df['cgpa'].astype(int)
df

    cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

In [5]:
df['cgpa'] = df['cgpa'].add(10)
df

    cgpa  resume_score  placed
0     28          6.52       1
1     26          5.17       0
2     28          8.86       1
3     26          7.27       1
4     27          7.30       1
..   ...           ...     ...
95    26          6.38       0
96    28          7.76       1
97    26          7.78       0
98    28          5.63       1
99    26          6.61       0

[100 rows x 3 columns]

In [6]:
df['cgpa'] = df['cgpa']+10
df

    cgpa  resume_score  placed
0     38          6.52       1
1     36          5.17       0
2     38          8.86       1
3     36          7.27       1
4     37          7.30       1
..   ...           ...     ...
95    36          6.38       0
96    38          7.76       1
97    36          7.78       0
98    38          5.63       1
99    36          6.61       0

[100 rows x 3 columns]

In [21]:
r = df['cgpa'].mean()
r

np.float64(16.47)

In [24]:
s = df['cgpa'].median()
s

16.0

In [26]:
g = df.filter(items = ['cgpa','placed'])
g
df[['cgpa', 'placed']]

    cgpa  placed
0     18       1
1     16       0
2     18       1
3     16       1
4     17       1
..   ...     ...
95    16       0
96    18       1
97    16       0
98    18       1
99    16       0

[100 rows x 2 columns]

In [28]:
s = df.filter(items=[5,6], axis=0)  #  axis=0 means row wise operation
s

   cgpa  resume_score  placed
5    18          6.19       1
6    15          7.09       0

In [29]:
df.to_string()  # save in string

'    cgpa  resume_score  placed\n0     18          6.52       1\n1     16          5.17       0\n2     18          8.86       1\n3     16          7.27       1\n4     17          7.30       1\n5     18          6.19       1\n6     15          7.09       0\n7     16          6.29       0\n8     16          6.71       0\n9     17          7.12       1\n10    16          6.35       0\n11    15          6.54       0\n12    16          7.01       0\n13    18          5.09       1\n14    17          6.25       1\n15    18          5.93       1\n16    18          7.64       1\n17    17          8.71       1\n18    15          5.88       0\n19    16          8.11       1\n20    15          8.06       0\n21    16          7.64       0\n22    16          5.77       0\n23    16          7.13       0\n24    18          6.18       1\n25    17          5.68       1\n26    16          6.47       0\n27    15          6.15       0\n28    17          7.67       1\n29    16          7.30       0\n30    17          7.15       1\n31    15          7.02       0\n32    15          7.96       0\n33    18          7.73       1\n34    18          7.19       1\n35    18          7.48       1\n36    18          7.56       1\n37    19          8.21       1\n38    16          8.72       0\n39    17          6.19       1\n40    18          5.32       1\n41    18          5.15       1\n42    16          6.91       1\n43    18          7.95       1\n44    15          5.92       0\n45    18          5.44       1\n46    15          5.21       0\n47    17          8.14       1\n48    15          6.57       0\n49    15          6.73       0\n50    18          6.74       1\n51    16          7.39       0\n52    15          7.50       0\n53    16          7.16       0\n54    15          7.18       0\n55    16          6.87       1\n56    16          6.43       0\n57    16          7.21       0\n58    16          7.37       0\n59    15          7.57       0\n60    15          6.64       0\n61    16          7.96       1\n62    15          8.43       0\n63    18          7.58       1\n64    17          8.09       1\n65    16          8.75       0\n66    18          8.02       1\n67    16          6.81       1\n68    16          7.49       0\n69    18          9.06       1\n70    17          7.41       1\n71    17          8.22       1\n72    17          7.98       1\n73    15          6.48       0\n74    15          7.36       0\n75    16          7.94       1\n76    19          5.50       1\n77    15          6.92       0\n78    15          5.66       0\n79    15          7.28       0\n80    17          7.70       1\n81    16          6.72       0\n82    17          6.06       1\n83    17          8.08       1\n84    15          6.49       0\n85    16          5.46       0\n86    16          5.76       0\n87    15          5.05       0\n88    18          6.07       1\n89    15          7.49       0\n90    15          5.56       0\n91    18          6.30       1\n92    15          6.18       0\n93    19          7.39       1\n94    18          4.95       1\n95    16          6.38       0\n96    18          7.76       1\n97    16          7.78       0\n98    18          5.63       1\n99    16          6.61       0'

In [44]:
d = df.to_dict()  # save in dictonary
# d

In [31]:
idx = df.columns 
idx

Index(['cgpa', 'resume_score', 'placed'], dtype='object')

In [32]:
label = df.columns[0]  # first column label 
label

'cgpa'

In [35]:
df.columns.values  # array of labels

array(['cgpa', 'resume_score', 'placed'], dtype=object)

In [40]:
p = df.rename(columns={'cgpa' : 'updated_cgpa', 'resume_score' : 'semester_marks'})    # rename columns
p

    updated_cgpa  semester_marks  placed
0             18            6.52       1
1             16            5.17       0
2             18            8.86       1
3             16            7.27       1
4             17            7.30       1
..           ...             ...     ...
95            16            6.38       0
96            18            7.76       1
97            16            7.78       0
98            18            5.63       1
99            16            6.61       0

[100 rows x 3 columns]

In [42]:
df['half'] = df['cgpa'].where(df['cgpa']>17, other=0)
df

    cgpa  resume_score  placed  half
0     18          6.52       1    18
1     16          5.17       0     0
2     18          8.86       1    18
3     16          7.27       1     0
4     17          7.30       1     0
..   ...           ...     ...   ...
95    16          6.38       0     0
96    18          7.76       1    18
97    16          7.78       0     0
98    18          5.63       1    18
99    16          6.61       0     0

[100 rows x 4 columns]

#### Data
##### 1. Numerical 
    * Continous data 
    * We can divide further 
    * salary -> 20654.65, weight -> 40.6, distance, height, age 
##### 2. Categorical 
    * Descrete data 
    * we can not divide further
    * gender, marital status, number of employees in an office