In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('tips - tips.csv')
df.sample(5)

     total_bill  tip     sex smoker   day    time  size
78        22.76  3.0    Male     No  Thur   Lunch     2
160       21.50  3.5    Male     No   Sun  Dinner     4
167       31.71  4.5    Male     No   Sun  Dinner     4
145        8.35  1.5  Female     No  Thur   Lunch     2
47        32.40  6.0    Male     No   Sun  Dinner     4

In [23]:
df.iloc[11:14]

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4

In [31]:
df = df.rename(columns={'sex' : 'gender', 'smoker' : 'smoke'})    # rename columns
df

     total_bill   tip  gender smoke   day    time  size male_customers
0            16  1.01  Female    No   Sun  Dinner     2              0
1            10  1.66    Male    No   Sun  Dinner     3           Male
2            21  3.50    Male    No   Sun  Dinner     3           Male
3            23  3.31    Male    No   Sun  Dinner     2           Male
4            24  3.61  Female    No   Sun  Dinner     4              0
..          ...   ...     ...   ...   ...     ...   ...            ...
239          29  5.92    Male    No   Sat  Dinner     3           Male
240          27  2.00  Female   Yes   Sat  Dinner     2              0
241          22  2.00    Male   Yes   Sat  Dinner     2           Male
242          17  1.75    Male    No   Sat  Dinner     2           Male
243          18  3.00  Female    No  Thur  Dinner     2              0

[244 rows x 8 columns]

In [32]:
df['total_bill'] = df['total_bill'].astype(int)
df

     total_bill   tip  gender smoke   day    time  size male_customers
0            16  1.01  Female    No   Sun  Dinner     2              0
1            10  1.66    Male    No   Sun  Dinner     3           Male
2            21  3.50    Male    No   Sun  Dinner     3           Male
3            23  3.31    Male    No   Sun  Dinner     2           Male
4            24  3.61  Female    No   Sun  Dinner     4              0
..          ...   ...     ...   ...   ...     ...   ...            ...
239          29  5.92    Male    No   Sat  Dinner     3           Male
240          27  2.00  Female   Yes   Sat  Dinner     2              0
241          22  2.00    Male   Yes   Sat  Dinner     2           Male
242          17  1.75    Male    No   Sat  Dinner     2           Male
243          18  3.00  Female    No  Thur  Dinner     2              0

[244 rows x 8 columns]

In [39]:
df['male_customers'] = df['gender'].where(df['gender']=='Male', other=0)
df['male_customers'].replace('Male', 1, inplace=True)
df

C:\Users\pc\AppData\Local\Temp\ipykernel_10276\2100180718.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['male_customers'].replace('Male', 1, inplace=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_10276\2100180718.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['male_customers'].replace('Male', 1, inplace=True)

     total_bill   tip  gender smoke   day    time  size  male_customers
0            16  1.01  Female    No   Sun  Dinner     2               0
1            10  1.66    Male    No   Sun  Dinner     3               1
2            21  3.50    Male    No   Sun  Dinner     3               1
3            23  3.31    Male    No   Sun  Dinner     2               1
4            24  3.61  Female    No   Sun  Dinner     4               0
..          ...   ...     ...   ...   ...     ...   ...             ...
239          29  5.92    Male    No   Sat  Dinner     3               1
240          27  2.00  Female   Yes   Sat  Dinner     2               0
241          22  2.00    Male   Yes   Sat  Dinner     2               1
242          17  1.75    Male    No   Sat  Dinner     2               1
243          18  3.00  Female    No  Thur  Dinner     2               0

[244 rows x 8 columns]

In [40]:
df.head(6)

   total_bill   tip  gender smoke  day    time  size  male_customers
0          16  1.01  Female    No  Sun  Dinner     2               0
1          10  1.66    Male    No  Sun  Dinner     3               1
2          21  3.50    Male    No  Sun  Dinner     3               1
3          23  3.31    Male    No  Sun  Dinner     2               1
4          24  3.61  Female    No  Sun  Dinner     4               0
5          25  4.71    Male    No  Sun  Dinner     4               1

In [43]:
df.to_excel('Tips.xlsx')