In [157]:
import numpy as np
import pandas as pd

In [158]:
df = pd.read_csv('/content/covid_toy.csv')
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [159]:
# 1 what is d/f b/w series and data frame

In [160]:
# Series =>
# This is 1D array
# this is a part of Dataframe
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [161]:
# DataFrame =>
# This is 2D array
# This is like a table
# it's each columns are series
df1 = pd.DataFrame({
    'Name' : ['Abhishek', 'Abhi', 'Khushi'],
    'Marks' : [90,70,82]
})
df1

       Name  Marks
0  Abhishek     90
1      Abhi     70
2    Khushi     82

In [162]:
# 2 d/f b/w loc and iloc

In [163]:
# loc =>
# We can get specific values using the name of columns
df.loc[:,'age']

0     60
1     27
2     42
3     31
4     65
      ..
95    12
96    51
97    20
98     5
99    10
Name: age, Length: 100, dtype: int64

In [164]:
# iloc =>
# We can get specific values using the index nunmber of columns
df.iloc[1:10, 2:4]

   fever   cough
1  100.0    Mild
2  101.0    Mild
3   98.0    Mild
4  101.0    Mild
5    NaN    Mild
6  101.0  Strong
7    NaN  Strong
8  100.0  Strong
9  101.0    Mild

In [165]:
# 3 what is d/f b/w decribe and info

In [166]:
# Describe ->
# It gives the statical view of our data
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [167]:
# Info ->
# It gives us the data type of each column and
# how much it using memory
# And is how many not null values are present in every column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [168]:
# 4 what is d/f b/w head  tail sample

In [169]:
# head -> It gives us the top 5 data
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [170]:
# tail -> It gives us the bottom top 5 data
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [171]:
# sample -> it give randomly a row from data
df.sample()

    age gender  fever   cough     city has_covid
73   34   Male   98.0  Strong  Kolkata       Yes

In [172]:
# 5 How do you handle missing values using pandas

In [173]:
# first we find the the null values using isnull().sum()
# second if there any null value present then
# we fill it by mean or meadian
# If there is many null values in a column then we drop that column

In [174]:
df.isnull().sum() # There are 10 null values in fever column

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [175]:
df['fever'].fillna(df['fever'].mean(), inplace=True)

/tmp/ipykernel_16335/425342757.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fever'].fillna(df['fever'].mean(), inplace=True)

In [176]:
# 6 How do you filter data -> by row and by column

In [177]:
# data filterd where age is less then 18
df[df['age']<18]

    age  gender  fever   cough       city has_covid
6    14    Male  101.0  Strong  Bangalore        No
20   12    Male   98.0  Strong  Bangalore        No
24   13  Female  100.0  Strong    Kolkata        No
28   16    Male  104.0    Mild    Kolkata        No
30   15    Male  101.0    Mild      Delhi       Yes
51   11  Female  100.0  Strong    Kolkata       Yes
59    6  Female  104.0    Mild    Kolkata       Yes
63   10    Male  100.0    Mild  Bangalore        No
75    5    Male  102.0    Mild    Kolkata       Yes
77    8  Female  101.0    Mild    Kolkata        No
78   11    Male  100.0    Mild  Bangalore       Yes
80   14  Female   99.0    Mild     Mumbai       Yes
83   17  Female  104.0    Mild    Kolkata        No
85   16  Female  103.0    Mild  Bangalore       Yes
88    5  Female  100.0    Mild    Kolkata        No
95   12  Female  104.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [178]:
df[['age', 'has_covid']]

    age has_covid
0    60        No
1    27       Yes
2    42        No
3    31        No
4    65        No
..  ...       ...
95   12        No
96   51       Yes
97   20        No
98    5        No
99   10       Yes

[100 rows x 2 columns]

In [179]:
# 7 What is group by perform operation using group by

In [180]:
# groupby =>
# In pandas groupby is a function by which we can group our data
# and then we can apply aggregation function on them

In [181]:
np.round(df.groupby('city')['age'].mean(), 0)

city
Bangalore    43.0
Delhi        49.0
Kolkata      42.0
Mumbai       45.0
Name: age, dtype: float64

In [182]:
# 8 export your data into csv and excel formate

In [191]:
df.to_csv('covid_csv_formate.csv')
df.to_excel('covid_excel_formate.xlsx')

In [184]:
# 9. How to rename a column
df.rename(columns={'age':'Age'}).head(3)

   Age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [185]:
# 10 if you have two subdataframes and a column is common
# now you have toh merge these two dataframes into a singal dataframe
df1 = df.groupby('city')['age'].mean().reset_index(name='avg_age')
df2 = df.groupby('city')['age'].mean().reset_index(name='avg_fever')
pd.merge(df1, df2, on = 'city')

        city    avg_age  avg_fever
0  Bangalore  43.266667  43.266667
1      Delhi  48.590909  48.590909
2    Kolkata  41.750000  41.750000
3     Mumbai  44.937500  44.937500

In [186]:
# 11 You have to update the values
# from 10 to 15 index number values of all columns

# df.iloc[10:16, :] = 'Undefined'

In [188]:
# 12 you have to convert categorical data into numerical data
df.head()
df['gender'] = df['gender'].map({'Male':1, 'Female':0})
df['cough'] = df['cough'].map({'Mild':0, 'Strong':1})
df['has_covid'] = df['has_covid'].map({'Yes':1, 'No':0})
df['city'] = df['city'].map({'Kolkata':0, 'Bangalore':1, 'Delhi':2, 'Mumbai':3})

In [189]:
df.head(5)

   age  gender  fever  cough  city  has_covid
0   60     NaN  103.0    NaN   NaN        NaN
1   27     NaN  100.0    NaN   NaN        NaN
2   42     NaN  101.0    NaN   NaN        NaN
3   31     NaN   98.0    NaN   NaN        NaN
4   65     NaN  101.0    NaN   NaN        NaN